default_language_version:
  python: python3.12 # set for project python version
repos:
  - repo: local
    hooks:
      - id: black-apply
        name: black-apply
        entry: uv run black
        language: system
        pass_filenames: true
        types: ["python"]
      - id: mypy
        name: mypy
        entry: uv run mypy
        exclude: tests/
        language: system
        pass_filenames: true
        types: ["python"]
      - id: ruff-apply
        name: ruff-apply
        entry: uv run ruff check --fix
        language: system
        pass_filenames: true
        types: ["python"]
      - id: pip-audit
        name: pip-audit
        entry: uv run pip-audit
        language: system
        pass_filenames: false