### This is the Terraform-generated prod-promote.yml workflow for the alma-webhook-lambdas-prod app repository ###
name: Prod Promote Lambda Container
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Prod Promote Lambda Container
    uses: mitlibraries/.github/.github/workflows/lambda-shared-promote-prod.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE_STAGE: alma-webhook-lambdas-gha-stage
      GHA_ROLE_PROD: alma-webhook-lambdas-gha-prod
      ECR_STAGE: "alma-webhook-lambdas-stage"
      ECR_PROD: "alma-webhook-lambdas-prod"
      FUNCTION: "alma-webhook-lambdas-prod"
 